name: ClockIN
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.3
  simple_animations: 1.3.3
  flutter_icons: 1.1.0
  flutter_bloc: 6.0.1
  flutter_spinkit: 4.1.2+1
  intl: 0.16.1
  flare_flutter: 2.0.6
  provider: 4.3.2
  mdi: 4.0.0
  camera: 0.5.8+5
  path: ^1.8.2
  path_provider: 1.6.11
  uuid: 2.2.0
  sembast: 2.4.7+6
  graphql_flutter: ^4.0.3-alpha.1
  http: ^0.13.5
  http_parser: ^4.0.2
  vertical_tabs: 0.2.0
  dio: ^5.0.3

  flutter_nfc_reader:
    path: ../dependencies/flutter-nfc-reader/
  flutter_clock_helper:
    path: ../dependencies/flutter_clock_helper/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf

  assets:
    - assets/
    - assets/images/
    - assets/animate/
    - assets/fonts/
